name: SCA Dependency Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 2'  # Weekly on Tuesdays

jobs:
  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Cache OWASP Dependency Check data
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository/org/owasp/dependency-check-data
          target/dependency-check-data
        key: ${{ runner.os }}-dependency-check-data-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-dependency-check-data-
          ${{ runner.os }}-dependency-check-
    
    # NVD API Key: Add NVD_API_KEY as a GitHub repository secret to avoid 403/404 errors
    # and significantly improve update performance. Without this key, updates can take a very long time.
    - name: Run OWASP Dependency Check
      run: |
        mvn org.owasp:dependency-check-maven:9.0.9:check \
          -DfailBuildOnCVSS=7 \
          -DsuppressOnlyInEffectedScope=true \
          -Dformats=HTML,JSON \
          -DdataDirectory=target/dependency-check-data \
          -DcentralAnalyzerEnabled=false \
          -DretireJsAnalyzerEnabled=false \
          -DnodeAnalyzerEnabled=false \
          -DautoUpdate=true \
          -DnvdApiKey=${{ secrets.NVD_API_KEY }}
    
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-report
        path: target/dependency-check-report.*
    
    - name: Check for vulnerabilities in JSON report
      if: always()
      run: |
        if [ -f target/dependency-check-report.json ]; then
          echo "Dependency check completed. Check the uploaded artifacts for detailed results."
          # Extract vulnerability count from JSON report
          if command -v jq &> /dev/null; then
            VULN_COUNT=$(jq '.dependencies | map(select(.vulnerabilities != null)) | length' target/dependency-check-report.json 2>/dev/null || echo "0")
            echo "Found $VULN_COUNT dependencies with vulnerabilities"
          fi
        else
          echo "No dependency check report found"
        fi

  dependabot-auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    
    - name: Auto-merge patch and minor updates
      if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}